### ISSUE TITLE
Request wiki permission

### ISSUE THREAD

**Issue by daijyc** [myui/hivemall#167]
I have a bunch of wiki about using hivemall for Pig. Can anyone help to merge back, or grant me the permission, so I can do it by myself?

**Comment by daijyc** [comment]
Here is the Pig wiki page:
https://github.com/daijyc/hivemall/wiki/PigHome

**Comment by myui** [comment]
Added a link in the front page: 
https://github.com/myui/hivemall/wiki

When your patch to Hive/Pig was accepted, I would merge your contents in Hivemall wiki.

Thanks!

**Comment by daijyc** [comment]
Thanks!
