### ISSUE TITLE
Question about "clustering algorithm"

### ISSUE THREAD

**Issue by yamitzky** [myui/hivemall#187]
I would like to do clustering with hivemall.

In README.md, no clustering algorithm are listed explicitly.
But in [read-the-docs document](http://hivemall-docs.readthedocs.org/en/latest/Recommendation-using-Min-wise-LSH-%28minhash%29/), I found an example query about "Extract clusters".

Can MinHash be used for clustering, and is there any other clustering algorithm?

(Sorry that I couldn't label "question")

**Comment by myui** [comment]
A simple Minhash is only supported in Hivemall to do clustering.
https://github.com/myui/hivemall/wiki/Recommendation-using-Min-wise-LSH-(minhash)

In Minhash, hashing is used to assign cluster*s* to a feature vector. The [feature vector format](https://github.com/myui/hivemall/wiki/Input-Format-for-classification-and-regression) is a common format of Hivemall.

| cluster id | userid |
| ------------ | -------- |
| C1 | userA,userB |
| C2 | userC |
| C3 | userB,userC |
| C4 | userA,userC |
| .. | .. | 

There are two parameters in Minhash as follows:
```sql
-- (maximum) number of clusters to assign for each row
set hivevar:hashes=5; -- Generate N sets of minhash values for each row (DEFAULT: 5)

-- K minimum hash values are used to generate a cluster id.
set hivevar:keygroups=2; -- Use K minhash values (DEFAULT: 2)

create table news20_clusterid_assign
as
select 
  -- minhash(rowid, features) as (clusterId, rowid)
  minhash(rowid, features, "-n ${hashes} -k ${keygroups}") as (clusterId, rowid)
from 
  news20mc_train;
```

You can avoid tiny clusters using a `having` clause as follows: 
```sql
set hivevar:min_cluster_size=5;
create or replace view news20_cluster
as
select
  clusterId, 
  collect_set(rowid) as rowids
from 
  news20_clusterid_assign
group by clusterId
having size(rowids) > ${min_cluster_size};
```

**Comment by yamitzky** [comment]
Thank you for your kind answer.

So, in the clustering phase, the Min-wise LSH does probabilistic clustering so that users belongs to one or more clusters like the cluster-user table. And then, in the recommendation phase, users who belongs to same clusters are recommended, right?

Now I get it, thanks!

**Comment by myui** [comment]
You are right. 

kNN search is also useful for finding similar users.
