### ISSUE TITLE
Support spark environments

### ISSUE THREAD

**Issue by maropu** [myui/hivemall#216]
The current Apache Spark implementation cannot handle some parts of hivemall correctly;
 - it does not initialise o.a.h.hive.ql.exec.MapredContext
 - it has limited supports for o.a.h.hive.ql.exec.UDF

Basically, the codes of hivemall-spark below will be ported into hivemall.
https://github.com/maropu/hivemall-spark/tree/master/src/main/java/hivemall

**Comment by myui** [comment]
Please make a separated module, e.g., spark or spark_porting, for adding additional wrapper for Spark.

**Comment by maropu** [comment]
Ok, I'll try it.

**Comment by myui** [comment]
merged
https://github.com/myui/hivemall/pull/287
