### ISSUE TITLE
Add R2 UDAF

### ISSUE THREAD

**Issue by myui** [myui/hivemall#257]
https://github.com/myui/hivemall/wiki/Statistical-evaluation-of-a-prediction-model

**Comment by y-ken** [comment]
:+1: 

https://github.com/myui/hivemall/blob/7d650f665356717617d4399735c873f40bc4609f/resources/ddl/define-macros.hive

**Comment by myui** [comment]
@y-ken Hive macro CANNOT contain any UDAF. So, we need to create UDAF for R2 computation.

**Comment by ArnabRaxit** [comment]
@myui I am interested and might be able to help with this. Note, I didn't find any tests for any of the code in evaluation package. Are there?

**Comment by myui** [comment]
@ArnabRaxit Thank you for the help.

R2 can be computed by SQL as seen in the following link but better to provide R2 UDAF.
https://github.com/myui/hivemall/wiki/Statistical-evaluation-of-a-prediction-model

You can find implementations of other evaluation metrics for reference in
https://github.com/myui/hivemall/tree/master/core/src/main/java/hivemall/evaluation

I did not created unit tests for them. Put unit tests on `core/src/test/java/hivemall//evaluation` if possible.
https://github.com/myui/hivemall/tree/master/core/src/test/java/hivemall//evaluation

**Comment by myui** [comment]
Merged PR. Will be included from `v0.4.1-alpha.6`.
https://github.com/myui/hivemall/pull/268
