### ISSUE TITLE
Propose Hivemall to Apache Incubator

### ISSUE THREAD

**Issue by myui** [myui/hivemall#280]

**Comment by maropu** [comment]
+1

**Comment by myui** [comment]
Now on-going ...

https://wiki.apache.org/incubator/HivemallProposal
http://markmail.org/thread/mjwyyd4btthk3626#query:+page:1+mid:mjwyyd4btthk3626+state:results

**Comment by myui** [comment]
Accepted!!

http://markmail.org/thread/tebzbib4guntjw32

**Comment by maropu** [comment]
congrats. Do we need to make another entry to track issues such as legal ones just after apache incubator activities started?
