### ISSUE TITLE
question about hivemall install

### ISSUE THREAD

**Issue by iwatobipen** [myui/hivemall#331]
Dear, 
When I tried to install hivemall, I got following error message.
hive> add jar /tmp/hivemall-core-0.4.2-rc.1-with-dependencies.jar;
hive> source /tmp/define-all.hive;
.....
FAILED: SemanticException [Error 10301]: Cannot drop native function sha1
Also type directory drop command give same error. 
hive> drop temporary function sha1;
FAILED: SemanticException [Error 10301]: Cannot drop native function sha1

I wonder if someone can give me some advice or comments.
Best regards.

**Comment by myui** [comment]
@iwatobipen 

Related to #320 

Since v1.3.0, Hive has a native `sha1` function. So, please comment out 
`drop temporary function sha1` and `create temporary function sha1` in `define-all.hive`.

**Comment by iwatobipen** [comment]
Dear,
Thank you for your quick response!
It works fine!
Best regards,
Taka

**Comment by MarsXDM** [comment]
it's really helpful for me.

**Comment by imargon** [comment]
I also have the same problem ,now the hive cannot start up. how I remove the hivemall?

**Comment by myui** [comment]
@imargon How do you install Hivemall?

 When adding jar on Hive on a Hive cli session, you don't need to uninstall. Just exit the session.
