### ISSUE TITLE
IP-clearance (SGA) from TD contributors

### ISSUE THREAD

**Issue by myui** [myui/hivemall#381]
To Hivemall contributors from the current and past Treasure Data's employees (@naritta @L3Sota @takuti @amaya382 @NaokiStones @ryukobayashi )

[In the process](http://incubator.apache.org/guides/mentor.html#initial-ip-clearance) of Apache Incubation, we need to clear all IPs of Hivemall.
https://issues.apache.org/jira/browse/HIVEMALL-9

Instead of collecting [SGAs](https://www.apache.org/licenses/software-grant-template.pdf) from each one of you, I'm considering to collect the [attached SGA](https://github.com/myui/hivemall/files/582724/software-grant-td.pdf) (not signed yet) from Treasure Data assuming  the company holds all Copyrights of your contributions to Hivemall for your works at Treasure Data.

If you agree with it, please reply in this thread. _I need your reply to confirm it for an evidence._

Alternatively, you can be a committer of Hivemall signing to [I-CLA](http://apache.org/licenses/icla.pdf) though [community voting is required](http://incubator.apache.org/guides/ppmc.html) to be a committer. BTW, I'll invite some of you as committers because there are some [pending PRs](https://github.com/myui/hivemall/pulls) that is not yet merged and needs your help for merging them.

Thanks in advance,
Makoto

**Comment by naritta** [comment]
I agree with it.

**Comment by ryukobayashi** [comment]
👍

**Comment by myui** [comment]
@naritta @ryukobayashi Thanks!

**Comment by NaokiStones** [comment]
I agree with it.

**Comment by myui** [comment]
@NaokiStones Thanks!

**Comment by takuti** [comment]
I agree 👍

**Comment by amaya382** [comment]
I agree

**Comment by L3Sota** [comment]
@myui I agree with the above.

**Comment by myui** [comment]
@takuti @amaya382 @L3Sota Thanks!

Got all replies :-)
