### ISSUE TITLE
Building Hivemall XGBoost Integration 0.4.2-rc.2 Failed

### ISSUE THREAD

**Issue by MarsXDM** [myui/hivemall#388]
Hi all,
     I download the hivemall src and using bin/spark-shell to build it with spark 2.1.0,but it occurs such error:
[ERROR] Failed to execute goal on project hivemall-xgboost: Could not resolve dependencies for project io.github.myui:hivemall-xgboost:jar:0.4.2-rc.2: Failure to find ml.dmlc:xgboost4j:jar:0.10 in https://repository.cloudera.com/artifactory/cloudera-repos/ was cached in the local repository, resolution will not be reattempted until the update interval of cloudera has elapsed or updates are forced -> [Help 1]

it seems like the xgboost is missing,  what can I do to solve this problem ?

**Comment by myui** [comment]
This repository is deprecated. Moved to https://lists.apache.org/thread.html/758bca12bbf64360c84b5e1dbcec69e54a9cb8d0381705bf09c73bb2@%3Cuser.hivemall.apache.org%3E
